Fix buffer overflow issue when converting strings from JNI to Dart
dart-lang/jnigen pull request #416
Opened 2023-11-02 20:18 UTC by slightfoot

Test out this flutter app with jni: 0.7.0 on an Android device and you will receive the following output:
```plain
Launching lib\main.dart on Pixel 4 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app-debug.apk...
Debug service listening on ws://127.0.0.1:59650/oKyS4sWS_K4=/ws
Syncing files to device Pixel 4...
I/flutter (10682): packageName: com.example.jnitest됀
```

```dart
import 'package:flutter/material.dart';
import 'package:jni/jni.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  final obj = JObject.fromRef(Jni.getCurrentActivity());
  final packageName = obj.callMethodByName<String>(
    'getPackageName',
    '()Ljava/lang/String;',
    [],
  );
  print('packageName: $packageName');
}
```

Notice the string has extra characters at the end: `com.example.jnitest됀` of the package name.

This is because the current implementation overflows when reading the characters for strings. If the memory for the string originates in a buffer that was null terminated this is not an issue. But this cannot be guaranteed. Instead this PR patches the requirement to fetch the length of the string before we read the characters. 

This run over on reading can lead to an infinite-loop/crash on reading as it will either carry on reading into invalid memory or simply overrun at some point.

It is also good to note that the official [JNI docs for GetStringChars](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#GetStringChars) does not mention the returned jchar* as being null terminated. So we should not expect it.

There was two places in the code that `toDartString` was implemented. This was also part of the underlying cause because the two implementations were different. This PR also patches the code so that one calls the other and they both end up using the same implementation. 

I have also ensured the tests are updated to validate UTF-8 and UTF-16 implementations. I wanted to test the unhappy case where the originating string is not null terminated, but with strings created on my local machine I cannot replicate. I can however replicate on Android as the test above shows. 

@HosseinYousefi I see you are working on 0.8.0 so I have chosen not to update the CHANGELOG or pubspec and let you do that as required.

2023-11-03 09:05 UTC, HosseinYousefi approved these changes
LGTM! Thanks for your contribution @slightfoot!

2023-11-03 09:09 UTC, HosseinYousefi requested changes

2023-11-03 09:09 UTC, HosseinYousefi commented on jni/lib/src/lang/jstring.dart
> -    final result = chars.cast<Utf16>().toDartString(length: length);
With this cast removed, `package:ffi` is no longer needed. Please remove the import to make the analyzer happy!

```
warning • Unused import: 'package:ffi/ffi.dart' • lib/src/lang/jstring.dart:7:8 • unused_import
```

2023-11-03 09:24 UTC, merged

2023-11-03 09:31 UTC, HosseinYousefi commented
Published `0.7.2` with the fix.

2023-11-07 13:53 UTC, slightfoot commented
@HosseinYousefi Would it be good to notify the packages that depend on jni about his one? maybe the dart ones like cronet_http?

2023-11-07 13:56 UTC, HosseinYousefi commented
> @HosseinYousefi Would it be good to notify the packages that depend on jni about his one? maybe the dart ones like cronet_http?

It's a good idea! cc/ @brianquinlan.

2023-11-07 19:17 UTC, brianquinlan commented
Thanks for the heads-up. I'll publish a cronet_http version with a 0.7.2 lower-bound right away.